// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('app', ['ngRoute', 'controllers']);

  app.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        controller: 'ListController',
        templateUrl: '/app/{{name}}/tpl/list.tpl.html'
      });
    }
  ]);

}).call(this);
