// Generated by CoffeeScript 1.7.1
(function() {
  var services;

  services = angular.module('services', ['ngResource']);

  services.factory('Model', [
    '$resource', function($resource) {
      return $resource('/rest/{{name}}/:id');
    }
  ]);

}).call(this);
