// Generated by CoffeeScript 1.7.1
(function() {
  var services;

  services = angular.module('services', ['ngResource']);

  services.factory('Model', function($resource) {
    return $resource('/rest/{{name}}/:id', null, {
      update: {
        method: 'PUT'
      }
    });
  });

}).call(this);
