// Generated by CoffeeScript 1.7.1
(function() {
  var cronsDir, express, f, file, files, fs, m, name, path, router, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref;

  express = require('express');

  path = require('path');

  fs = require('fs');

  router = express.Router();

  if (fs.existsSync(path.join(__dirname, '../permissions/defaultPermission.js'))) {
    router.all('*', require('../permissions/defaultPermission.js'));
  }

  files = fs.readdirSync(path.join(__dirname, '../permissions'));

  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    if (m = file.match(/^(\w+)Permission\.js$/)) {
      name = m[1];
      if (name !== 'default') {
        router.all("/" + name, require("../permissions/" + name + "Permission"));
        router.all("/rest/" + name, require("../permissions/" + name + "Permission"));
      }
    }
  }

  router.get('/', function(req, res) {
    return res.redirect('/{{DEFAULT_APP}}');
  });

  files = fs.readdirSync(path.join(__dirname, '../controllers'));

  for (_j = 0, _len1 = files.length; _j < _len1; _j++) {
    file = files[_j];
    if (m = file.match(/^(\w+)Controller\.js$/)) {
      name = m[1];
      router.use("/" + name, require("../controllers/" + name + "Controller"));
    }
  }

  files = fs.readdirSync(path.join(__dirname, '../restful'));

  for (_k = 0, _len2 = files.length; _k < _len2; _k++) {
    file = files[_k];
    if (m = file.match(/^(\w+)Restful\.js$/)) {
      name = m[1];
      if (name !== 'base') {
        router.use("/rest/" + name, require("../restful/" + name + "Restful"));
      }
    }
  }

  cronsDir = path.join(__dirname, '../crons');

  if (fs.existsSync(cronsDir)) {
    _ref = fs.readdirSync(cronsDir);
    for (_l = 0, _len3 = _ref.length; _l < _len3; _l++) {
      f = _ref[_l];
      if (m = f.match(/(\w+).js/)) {
        require("../crons/" + f);
      }
    }
  }

  module.exports = router;

}).call(this);
