// Generated by CoffeeScript 1.7.1
(function() {
  var User, config, express, router, _;

  express = require('express');

  User = require('../models/user');

  _ = require('underscore');

  config = require('../config');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('login');
  });

  router.post('/', function(req, res) {
    var password, username, _ref;
    _ref = req.body, username = _ref.username, password = _ref.password;
    if (username === 'root' && password === config.rootSecret) {
      req.session.user = {
        username: username,
        admin: true
      };
      return res.redirect('../');
    } else {
      return res.render('login', {
        err: '用户名或密码错误'
      });
    }
  });

  module.exports = router;

}).call(this);
