// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    req.session.user = null;
    return res.redirect('../');
  });

  module.exports = router;

}).call(this);
