// Generated by CoffeeScript 1.7.1
(function() {
  var Model, baseRestful;

  baseRestful = require('./baseRestful');

  Model = require('../models/{{name}}');

  module.exports = baseRestful(Model);

}).call(this);
