// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('baseApp', {
      module: '{{name}}',
      title: '{{label}}'
    });
  });

  module.exports = router;

}).call(this);
