// Generated by CoffeeScript 1.7.1
(function() {
  var crypto;

  crypto = require('crypto');

  exports.cipher = function(data, key) {
    var cipher, enciphered;
    cipher = crypto.createCipher('aes-128-ecb', key);
    enciphered = cipher.update(data, 'utf8', 'base64');
    enciphered += cipher.final('base64');
    return enciphered;
  };

}).call(this);
