// Generated by CoffeeScript 1.7.1
(function() {
  var crypto, fs;

  fs = require('fs');

  crypto = require('crypto');

  exports.copyFile = function(source, target, cb) {
    var cbCalled, done, rd, wr;
    rd = fs.createReadStream(source);
    rd.on("error", function(err) {
      return done(err);
    });
    wr = fs.createWriteStream(target);
    wr.on("error", function(err) {
      return done(err);
    });
    wr.on("close", function(ex) {
      return done();
    });
    rd.pipe(wr);
    cbCalled = false;
    return done = function(err) {
      if (!cbCalled) {
        cb(err);
        return cbCalled = true;
      }
    };
  };

  exports.sha1OfFile = function(srcFile, cb) {
    var cbCalled, done, h, s;
    h = crypto.createHash('sha1');
    s = fs.createReadStream(srcFile);
    s.on('error', function(err) {
      return done(err);
    });
    s.on('data', function(d) {
      return h.update(d);
    });
    s.on('end', function() {
      return done(null, h.digest('hex'));
    });
    cbCalled = false;
    return done = function(err, sha1) {
      if (!cbCalled) {
        cb(err, sha1);
        return cbCalled = true;
      }
    };
  };

}).call(this);
