// Generated by CoffeeScript 1.7.1
(function() {
  var config, mysql, mysqlPool;

  mysql = require('mysql');

  config = require('../config');

  mysqlPool = mysql.createPool(config.mysql);

  module.exports = mysqlPool;

}).call(this);
