// Generated by CoffeeScript 1.7.1
(function() {
  var RegExpEscape, genNumPass, padzero, replaceAll;

  genNumPass = function(len) {
    var i, pass;
    if (len == null) {
      len = 6;
    }
    return pass = ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
        _results.push(Math.floor(Math.random() * 10));
      }
      return _results;
    })()).join('');
  };

  padzero = function(i, min) {
    var pad, str, _i;
    if (min == null) {
      min = 3;
    }
    str = "" + i;
    if (str.length < min) {
      pad = min - str.length;
      for (_i = 0; 0 <= pad ? _i < pad : _i > pad; 0 <= pad ? _i++ : _i--) {
        str = "0" + str;
      }
    }
    return str;
  };

  RegExpEscape = function(str) {
    return str != null ? str.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&") : void 0;
  };

  replaceAll = function(contentText, replaceText, withText) {
    return contentText.replace(new RegExp(RegExpEscape(replaceText), 'g'), withText);
  };

  module.exports = {
    genNumPass: genNumPass,
    padzero: padzero,
    RegExpEscape: RegExpEscape,
    replaceAll: replaceAll
  };

}).call(this);
