// Generated by CoffeeScript 1.7.1
(function() {
  var async, readline, _;

  readline = require('readline');

  async = require('async');

  _ = require('underscore');

  module.exports = function(questions, cb) {
    var rl, tasks;
    if (!questions) {
      return cb('no questions');
    }
    rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    tasks = [];
    _.each(questions, function(q, key) {
      return tasks.push(function(cb) {
        return rl.question("please input " + q[0] + " (" + (q[1] || '') + "):", function(answer) {
          answer = answer || q[1];
          if (!answer) {
            return cb('no answer');
          }
          return cb(null, {
            key: key,
            answer: answer
          });
        });
      });
    });
    if (!(tasks.length > 0)) {
      return cb('no questions');
    }
    return async.series(tasks, function(err, results) {
      var answers, r, _i, _len;
      rl.close();
      if (err) {
        return cb(err);
      }
      answers = {};
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        r = results[_i];
        answers[r.key] = r.answer;
      }
      return cb(null, answers);
    });
  };

}).call(this);
