// Generated by CoffeeScript 1.7.1
(function() {
  var client, config, redis;

  redis = require('redis');

  config = require('../config');

  client = redis.createClient(config.redis.port, config.redis.host);

  module.exports = client;

}).call(this);
