// Generated by CoffeeScript 1.7.1
(function() {
  var BaseModel;

  BaseModel = require('./baseModel');

  module.exports = new BaseModel({
    name: '{{name}}',
    id: 'id',
    schema: {
      name: {
        type: String,
        size: 45
      },
      createTime: Date,
      updateTime: Date
    },
    labels: {
      $model: '{{label}}',
      name: '名称',
      createTime: '创建时间',
      updateTime: '更新时间'
    }
  });

}).call(this);
