// Generated by CoffeeScript 1.7.1
(function() {
  var BaseModel;

  BaseModel = require('./baseModel');

  module.exports = new BaseModel({
    name: '{{name}}',
    id: 'id',
    orderBy: 'name',
    schema: {
      name: {
        type: String,
        size: 45
      },
      create: Date
    },
    labels: {
      $model: '{{label}}',
      name: '名称'
    }
  });

}).call(this);
